name: elementary_network_image_widget_flutter
description: Network image widget based on Elementary package

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  elementary: ^1.5.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
